### ISSUE TITLE
about your data and code

### ISSUE THREAD

**Issue by Haidong-Kang** [StanLei52/GEBD#1]
Hello, is there any difference between your code and BMN series? According to my understanding, this task should be the same label format as activitynet1.3. In addition, your dataset is 32x of ActivityNet, can you provide a feature file extracted by GEBD for us to use? Thank you

**Comment by StanLei52** [comment]
Hi, sorry for the late reply.
1. This code focuses on generic boundaries while BMN focuses on action proposal. Therefore, BMN tends to predicts the start and end of an action instance, but the GEBD aims at detecting all the generic boundaries. You can refer to the paper and dive into the dataset&annotation for more details.
2. Currently we do not provide features on GEBD but will do this in the future. For your reference, you can use features provided by winner in our workshop challenge, here is the repo: https://github.com/hello-jinwoo/LOVEU-CVPR2021.

Thanks

**Comment by Haidong-Kang** [comment]
Thank you
