### ISSUE TITLE
[Is it a bug?] Bug in evaluation notebook may undervalue PA

### ISSUE THREAD

**Issue by KosukeMizufune** [StanLei52/GEBD#2]
Hello. We found following **critical bug** in https://github.com/StanLei52/GEBD/blob/main/eval/eval_GEBD_k400.ipynb;

```
bdy_idx_list_smt = bdy_idx_save['bdy_idx_list_smt']*downsample # already offset, index starts from 0
```
Since `bdy_idx_save['bdy_idx_list_smt']` is list, `*` operation just repeats elements of `bdy_idx_save['bdy_idx_list_smt']` instead of multiplication. Note, this dictionary may be produced by following;
https://github.com/StanLei52/GEBD/blob/fde03f8f3e8db1e487a7f37b3f1be600bbe72a4f/BdyDet/k400/detect_event_boundary.py#L208

After we change notebook code to `np.array(...) * downsample`, F1 value on Kinetics-GEBD **reaches 0.398** (note, 0.242 in your original paper)!

Just in case, could you fix this bug and recheck your evaluation score? 

Thanks a lot.

**Comment by StanLei52** [comment]
Hi @KosukeMizufune, thank you for pointing this out. Actually we made this mistake when evaluating the PA method on Kinetics-GEBD and TAPOS. We will fix this bug and re-evaluate PA as per your suggestion, also we will accordingly update the results in our paper and corresponding ipynb files.

Thank you.

**Comment by StanLei52** [comment]
@KosukeMizufune FYI, we've updated the results for PA in two ipynb files.

**Comment by KosukeMizufune** [comment]
@StanLei52 Thank you for update.
Moreover, we found another bug when we explore the factor for non-negligible difference between our reproduced F1 (0.398) and your re-evaluated F1 (0.352);
```
bdy_idx_list_smt = np.array(bdy_idx_save['bdy_idx_list_smt'])*downsample
```
We think this operation is incorrect since indices are already multiplied in this line;

https://github.com/StanLei52/GEBD/blob/4db5955a1b012e12930616070ae0682fe984e883/BdyDet/k400/detect_event_boundary.py#L175

It seems that `offset` is `4 * 3 = 12` according to this line;

https://github.com/StanLei52/GEBD/blob/4db5955a1b012e12930616070ae0682fe984e883/BdyDet/k400/detect_event_boundary.py#L152

Note, `12` seems to be the last index in the first segment of a video (when `num_seq=2, seq_len=5, pred_step=1` according to https://github.com/StanLei52/GEBD/blob/main/PA_DPC/dpc/dataset_3d_infer_pred_error.py), `4` is downsampled index, and `3` is downsample factor.

Therefore, if `bdy_idx_save['bdy_idx_list_smt']` is following list `[12, 13, 14]`, `bdy_idx_list_smt` in evaluation notebook is `[36, 39, 42, …]` though it must be `[12, 15, 18]`.

I think you must rewrite notebook code as following (even though it is hard coding);
```
offset = 12
bdy_idx_list_smt = np.array(bdy_idx_save['bdy_idx_list_smt'] - offset)*downsample + offset
```

Could you confirm this issue again?

Thank you.

**Comment by StanLei52** [comment]
Thanks for pointing this out. We will confirm this and get back to you later :)

**Comment by StanLei52** [comment]
Hi @KosukeMizufune. We modified the codes in notebook as follows:
```python
offset = 12
bdy_idx_list_smt = (np.array(bdy_idx_save['bdy_idx_list_smt']) - offset)*downsample + offset
```
We re-evaluated PA on Kinetics-GEBD and here is our results:
```python
rec: 0.363428857573839
prec: 0.961768707482993
F1: 0.527021941664729

rec: [0.25916850445152334, 0.32879184060430905, 0.3554179866813215, 0.3684796887211294, 0.3769587436964836, 0.38216124672836443, 0.38645500819601414, 0.3895206514001979, 0.392401969342505, 0.3949329359165425]

prec: [0.8355497037524687, 0.9436910247970156, 0.9650647355716481, 0.9725696730305026, 0.9776607417160412, 0.9804696071977178, 0.982971253017336, 0.9846829054202326, 0.9864384463462804, 0.9885889839806891]

F1: [0.39562357781864654, 0.4876732212923272, 0.5195090546111774, 0.5344652935217791, 0.5441199819245471, 0.5499618423967898, 0.5547931632400297, 0.558220541401274, 0.5614578519415959, 0.564394888499123]
```
Feel free to contact us if there is any problem.

**Comment by KosukeMizufune** [comment]
@StanLei52 Thank you for re-evaluation! It seems to be good since the results are close to us (slight F1 difference might be due to the difference in available validation datasets).
