### ISSUE TITLE
Annotations for TAPOS Dataset

### ISSUE THREAD

**Issue by rayush7** [StanLei52/GEBD#4]
Hi @StanLei52 ,

I am trying to evaluate the code on TAPOS dataset. 

Could you please provide the raw annotation for TAPOS and the Jupyter Notebook to process it as provided for HMDB and Kinetics-GEBD?
https://github.com/StanLei52/GEBD/tree/main/data/export

**Comment by StanLei52** [comment]
Hi, for the TAPOS dataset, I downloaded the annotations released by the author as of Mar. 2021. I am not sure whether the author have updated the annotation to a new version. In addition, I noticed that the extracted frames are now released, while they were not available in 2021. 

At that time I downloaded the videos and extracted the video frames by myself. For some of the videos I got different FPS and thus different total frames. Therefore, for “substages”, I re-calculate the corresponding frame idx based on my extracted frames: TAPOS_frame_idx / TAPOS_total_frames * my total frames.

For the raw annotation and process code -- yes i can send you a copy of process code but for the annotation, i am not sure whether there exists license issues. If you need the code, pls reach out at leiwx52@gmail.com
